# Generated by Django 4.2 on 2024-01-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='settings',
            name='android_app',
            field=models.URLField(blank=True, null=True, verbose_name='Android App URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_us',
            field=models.EmailField(max_length=50, verbose_name='Email Us'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ios_app',
            field=models.URLField(blank=True, null=True, verbose_name='iOS App URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
