# Generated by Django 4.2 on 2024-01-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_adress_settings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
    ]
