# Generated by Django 4.2 on 2024-01-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
