# Generated by Django 4.2 on 2024-01-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cartdetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='order',
            new_name='cart',
        ),
    ]
