# Generated by Django 4.2 on 2023-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('FEATURE', 'FEATURE')], max_length=10, verbose_name='flag'),
        ),
    ]
