# Generated by Django 4.2 on 2023-12-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_review_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
