# Generated by Django 4.2 on 2023-12-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_image_brand_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='images',
            new_name='image',
        ),
    ]
