# Generated by Django 4.2 on 2024-01-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_images_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
