# Generated by Django 4.2 on 2024-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_ar',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('FEATURE', 'FEATURE')], max_length=10, null=True, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_en',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('FEATURE', 'FEATURE')], max_length=10, null=True, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_fr',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('FEATURE', 'FEATURE')], max_length=10, null=True, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ar',
            field=models.TextField(max_length=400, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(max_length=400, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_fr',
            field=models.TextField(max_length=400, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
    ]
