# Generated by Django 4.2 on 2024-02-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle_fr',
        ),
    ]
